site_name: "Peter Wooldridge"
site_url: https://quantably.co
repo_url: https://github.com/quantably/blog
repo_name: quantably/blog

plugins:
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      archive: true
      categories: true
      post_readtime: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home: index.md
  - Blog: blog/index.md
  - Media: media.md
  
extra:
  analytics:
    provider: google
    tracking_id: 'UA-XXXXXX-X'