site_name: "My Personal Site"
site_url: https://quantably.co
repo_url: https://github.com/quantably/blog
repo_name: quantably/blog


plugins:
  - blog:
      post_readtime: true

theme:
  name: material
  features:
    - navigation.tabs
    #- navigation.sections
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Blog: blog/index.md
  - About: about.md
  
extra:
  analytics:
    provider: google
    tracking_id: 'UA-XXXXXX-X'
